spring:
  application:
    name: micro01
  data:
    mongodb:
      ## aquí pondreis la URL que teneis de mongoAtlas, recordar que teneis que poner en la URl despues de .net/<basedatos>?retry...
      ## en caso de tener una mongo en local -> mongodb://localhost:27018/<basededatos>
      uri: mongodb+srv://root:root@recudiseno.e786z.mongodb.net/vedrunaApp?retryWrites=true&w=majority&appName=recuDiseno
  mail:
    host: smtp.gmail.com
    port: 587
    username: recudiseno@gmail.com
    password: hcni dwap dsgf ipmi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
springdoc:
  api-docs:
    enable: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
